"""Added ingestion_head

Revision ID: 59d1a621d7ce
Revises: 7bd07dae6188
Create Date: 2025-07-07 08:21:22.162725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d1a621d7ce'
down_revision: Union[str, Sequence[str], None] = '7bd07dae6188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_heads',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_heads')
    # ### end Alembic commands ###
