"""Added username and api_key to users

Revision ID: 8acd00c59a23
Revises: 176794d2e8e5
Create Date: 2025-07-06 12:42:45.340109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8acd00c59a23'
down_revision: Union[str, Sequence[str], None] = '176794d2e8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('api_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
