FROM python:3.11-slim

RUN apt-get update

WORKDIR /app

RUN pip install --no-cache-dir uvicorn sentence-transformers tenacity fastapi[standard] pydantic

RUN pip install pydantic-settings==2.10.1

COPY ./app ./app

CMD ["uvicorn", "app.core.factory.vectorizer_api:app", "--host", "0.0.0.0", "--port", "8050"]